# AWS Configuration
# Best practice: Store non-sensitive configuration here
# Sensitive data (keys, secrets) should be in environment variables or AWS credentials file

aws:
  region: "us-east-1" 
  
s3:
  buckets:
    source_bucket: "weather-data-store-bucket-11-07-2025-12-20-avar" 
    source_prefix: "openweather_api"
    processed_prefix: "processed"
    processed_file_name: "daily_weather.parquet"
  
dynamodb:
  tables:
    control_table_queue: "weather_collection_queue"
    control_table_progress: "weather_collection_progress" 
  
# Application settings
app:
  batch_size: 100
  retry_attempts: 3
  log_level: "INFO"
  weather_url_day: "https://api.openweathermap.org/data/3.0/onecall/day_summary"
  geocoding_by_zipcode_url: "http://api.openweathermap.org/geo/1.0/zip"
  weather_historical_flag : true
  daily_call_limit : 950
  weather_start_dt: 2020-01-01
  weather_end_dt: 2020-01-02
  zipcodes: 
    - zip_code: "10001"  # Manhattan
      country_code: "US"
    - zip_code: "10002"  # Lower East Side
      country_code: "US"
    - zip_code: "10003"  # East Village
      country_code: "US"
    - zip_code: "11201"  # Brooklyn Heights
      country_code: "US"
    - zip_code: "11101"  # Long Island City
      country_code: "US"
    - zip_code: "12084"  # Guilderland
      country_code: "US"
  ISO3166_code: "US" 
  header_user_agent : "WeatherApp/1.0"
  header_accept : "application/json"
